# Generated by Django 4.2.1 on 2023-06-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('romance', 'Romance'), ('epic', 'Epic')], max_length=100)),
                ('ratings', models.CharField(choices=[('5', '5 star'), ('4', '4 star'), ('3', '3 star'), ('2', '2 star'), ('1', '1 star')], max_length=100)),
                ('date_released', models.DateField()),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
