# Generated by Django 4.2.1 on 2023-06-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['id'], 'verbose_name': 'Movies', 'verbose_name_plural': 'Movies'},
        ),
    ]
